<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DocumentsTypeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('documents_type')->insert(['name_' => 'Acciones populares', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de adjudicación o Remate', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de aprobación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de audiencia', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de Comité', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de Conciliación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de Consejo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de entrega de inmueble entregado en arrendamiento', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de inicio', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de liquidación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de Obra', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de posesión', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de presentación personal del defensor de oficio', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de recibido', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de Reconocimiento Voluntario de Paternidad', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de reunión', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de terminación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta Equipo Operativo MIPG', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas Comité de Participación Local de Salud (COPACO)', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas Consejo de Política Económica y Social (COMPES)', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas Consejo de Política Social', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas Consejo Fondo de Vivienda de Interés Social (FOVIS)', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas Consejo Territorial de Planeación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas de finalización', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas de finalización del convenio', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas de Incautación de Mercancia', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas de Incautación de Sustancias Psicoactivas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas de Justicia Transicional', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actas de manifestación de interés para participar en el proceso', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acta de visita', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo de adjudicación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo de adopción', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo de apertura del proceso de contratación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo de aprobación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo de establecimiento del convenio', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto Administrativo de liquidacion oficial', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo de nombramiento o contrato de trabajo Oficio de notifi', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo de retiro o desvinculación del servidor de la entidad d', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo de secuestre', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo donde se notifica declaratoria de desierta', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo por el cual se adopta el Plan de vacaciones', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo por el cual se adopta el Plan de Bienestar Social y Est', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo por el cual se adopta el plan de trabajo anual del sist', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acto administrativo por el cual se adopta el Programa de Salud Ocupacional', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actos administrativos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actos administrativos de avaluos y soportes', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Actualización Escolar', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acuerdo de pago', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acuerdo del Concejo municipal o Decreto municipal de adopción del Plan Docu', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Acuerdos de Confidencialidad', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Adendas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Adendas a los términos de referencia', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Adición de afiliados o retiro cuando aplique', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Afiliaciones a: Régimen de salud (EPS) pensión cesantías caja de compensaci', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Análisis de riesgos previsible en el proceso', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Análisis del sector económico y de los oferentes', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Anexos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Antecedentes propios de tipo contractualInforme de Evaluación contemplando', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Anteproyecto del presupuesto de gastos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Anteproyecto del presupuesto de ingresos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Apoyo y Fortalecimiento Empresarial', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto apertura de investigación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto concediendo recurso de queja', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto corriendo traslado para alegar de conclusión', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de admisión', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de admisión de recurso', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de archivo', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de cierre de investigación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de conociemiento', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de incorporación y/o acumulación de expedientes', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de indagación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de investigación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de Mandamiento de pago', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de obedézcase y cúmplase lo resuelto por la segunda instancia', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de pliego de cargos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de prorroga en proceso de investigación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de pruebas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto de resolución de recurso', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto decretando pruebas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto inhibitorio', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto nombrando un defensor de oficio', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto que resuelve recursos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto resolviendo nulidad', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Auto resolviendo pruebas en descargos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Autorización Cambio de IPS', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Autorización de baja de bienes', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Autorizaciones de Modificación de Planos Urbanísticos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Autorizaciones de Movimiento de Tierras', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Autorizaciones de Propiedad Horizontal y sus Modificaciones', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Avaluo y/o peritaje', 'used_entrance' => 'N', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Avisos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Avisos de prensa', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Balance General', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Balance Inicial', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Banco de Proyectos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Banco Terminológico de series y subseries documentales', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Boleta citación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Boletin Epidemiológico Municipal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Cartografía oficial', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Ceriticaciones de Retiro de EPS', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificación bancaria', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificación de la vigencia de la tarjeta profesional de todos los profesi', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificacion de retiro de SISBEN', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificación de supervisión', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificación de supervisión para trámite de pago de contrato de compravent', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificación del nuevo del SISBEN', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificación individual de aduana para vehículos automotores', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificaciones', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificaciones de compensación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificaciones de devolución', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificaciones de estudio', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificaciones de estudios académicos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificaciones de experiencia de trabajo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificaciones De Uso Del Suelo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificaciones De Viabilidad Del Uso Del Suelo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificaciones Demarcaciones Del Inmueble', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de afiliación a la ARL', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de antecedentes disciplinarios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de antecedentes fiscales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de antecedentes judiciales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de aportes a parafiscales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de aportes a seguridad social', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de aportes parafiscales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de aptitud laboral (examen médico de ingreso)', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de Calibración', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de Disponibilidad Presupuestal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de disponibilidad presupuestal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de existencia y representación legal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de existencia y representación legal (personas Juridicas)', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de inscripción ante el RUNT Seguro Obligatorio-SOAT', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de insuficiencia o inexistencia de personal en planta', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de la Revisión Tecnicomecánica y de Emisiones Contaminantes', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de presentación del informe ejecutivo anual de evaluación al Si', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de registro presupuestal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado de tradición y libertad de inmueble', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado del SISBEN', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado finaciero de deuda cancelada', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificado registro presupuestal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificados de antecedentes fiscales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificados de Disponibilidad Presupuestal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificados de registro presupuestal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificados de Residencia', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Certificados de responsabilidad estructural', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Circulares', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Citaciones', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Comparendos fisicos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Comprobante contable de egresos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Comprobante contable de Ingreso', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Comprobante de Baja de bienes de almacén', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Comprobante de ingreso de bienes a almacén', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Comprobantes de contabilidad', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Compromisos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Comunicaciones con otras entidades', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Comunicaciones oficiales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Comunicaciones oficiales consecutivo PQRS', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Concepto de viabilidad', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Concepto del bien', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Concepto jurídico', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Conceptos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Conceptos De Normas Urbanísticas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Conceptos De Reparaciones Locativas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Conceptos Técnicos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Conceptos Técnicos Agropecuarios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Conceptos Técnicos Ambientales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Conciliación Bancaria', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Constancia ejecutoria', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Construcción adecuación y manetenimiento de andenes senderos peatonales y c', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Construcción ampliación y mantenimiento Infraestructura Fisica Educativa', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Construcción ampliación y mantenimiento Infraestructura Alumbrado Público', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Construcción ampliación y mantenimiento Infraestructura Adulto Mayor', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Construcción ampliación y mantenimiento Infraestructura Fisica Cultural', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Construcción ampliación y mantenimiento Infraestructura Fisica Deportiva', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Construcción ampliación y mantenimiento Infraestructura Personas Diversamen', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Construcción ampliación y mantenimiento Infraestructura Primera Infancia', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Contenido de la publicidad', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Contestación de la demanda', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Contestación del recurso', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Convocatorias de Emprendimiento', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Convocatorias públicas', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Copia certificado de libertad', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Copia de facturas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Copia recibo del impuesto predial cancelado', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Copias documentos de identidad', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Cronogramas de actividades', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Cuadros de clasificación documental', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Cuenta de cobro', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Datos de hogares Sisbenizados (software SISBEN III)', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaración de Bienes y Rentas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto Aportes y participaciones', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto de Aviso y Tableros', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto de Espectáculos Públicos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto de Industria y Comercio', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto de Multas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto de Rentas contractuales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto de Sobretasa a la Gasolina', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto de Tasas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto Predial', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Declaraciones por Recaudo de Impuesto Rifas Municipales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Decretos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Demanda', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Demarcación del predio', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Denuncia', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Derecho de petición', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Desarrollo de eventos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Designación de comité evaluador', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Despachos comisorios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Diagnostico', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Diagnóstico de las necesidades de aprendizaje', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Diagnóstico de necesidades', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Diagnostico documental', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Dictamen técnico del Consejo Consultivo de Ordenamiento Territorial en el q', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Diseño geometrico de via', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Diseño y Contrucción Sistema Aprovechamiento de Plantas de Tratamiento de', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Disponibilidad inmediata de servicios públicos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Documento Técnico de Soporte de la revisión que explica las decisiones adop', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Documentos requisitos postulante', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Dotación de unidades sanitarias', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Emplazamientom para decalrar y para corregir', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Entrega de Insumos agropecuariso', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Escrito de recurso', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Escrito descargos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Escrito recurso de apelación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Escritura Pública', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Especificaciones técnicas del producto o servicio', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estado de Cambios en el Patrimonio', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estado de Cambios en la Situación Financiera', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estado de Flujos de Efectivo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estado de Inventarios', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estado de Resultados', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estados de Costos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estados de Liquidación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estados Financieros Consolidados', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estados Financieros de Períodos Intermedios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estados Financieros Extraordinarios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estudio de conveniencia y oportunidad', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estudios de evaluación de factores de selección', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estudios de Suelos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estudios de viabilidad', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estudios jurídicos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estudios previos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estudios técnicos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Estudios técnicos de soporte sobre los hechos condiciones o circunstancias', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Evaluación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Evaluación inicial del sistema de seguridad y salud en el trabajo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Examen médico pre-ocupacional', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Extractos bancarios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Factura', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Fallo de primera instancia', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Fallo segunda instancia', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Fallos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Feria Dominical', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Ficha MGA', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Ficha Técnica', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Fichas de eventos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Fichas del SISBEN', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Formacion para el Emprendimiento', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Formato de Solicitud de Autorizaciones Eventos y Espectáculos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Formulario de cancelación de registro de contribuyentes del impuesto de ind', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Formulario unico nacional', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Fotocopia de la factura de servicios públicos domiciliarios de la vivienda', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Garantías', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Garantía única y/o de responsabilidad civil extracontractual', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Hoja de vida de la Función Pública para oferentes personas naturales y pers', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Hoja de vida de la Función Pública para personas naturales o personas juríd', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Incautaciones o embargos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Indicadores', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe de adjudicación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe de auditoría del Sistema de Gestión de Calidad', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe de Ejecución', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe de ejecución presupuestal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe de inconsistencias encontradas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe de interventoría', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe de supervisión de contrato', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe del plan', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe del plan Agropecuario Municipal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe ejecutivo anual de evaluación al Sistema de Control Interno', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe final de evaluación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe final de verificación del comité y calificación final', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe pasivo pensional', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe pormenorizado del estado de Control Interno', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe preliminar de evaluación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informe', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informes de Seguimiento', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'N', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informes de valoración psicológica', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'N', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informes de Gestión', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Informes Sistema de Salud Pública -SIVIGILA', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'N', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Inscripciones', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Instructivos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Instrumento de control del mantenimiento preventivo y correctivo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Intervención Metros Lineales de Alcantarillado', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Inventario de elementos devolutivos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Inventarios documentales- Transferencias', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Inventario documental archivo de gestión', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Inventarios de Bienes Generales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Inventarios de Bienes Individuales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Invitación pública', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Justificación de contratación directa', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Justificación del Anteproyecto', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Libros Auxiliares de Bancos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Libros Auxiliares de Caja', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Libros de Registro de Apropiaciones', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Libros de registros de cuentas por pagar', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Libros de registros de ingresos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Libros de Registros de Reservas Presupuestales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Libros de Registros de Vigencias Futuras', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Libros Diarios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Libros Mayores y de Balances', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Licencia de Construcción', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Licencias de exhumación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Licencias de Inhumación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Licencias de Transporte de Semovientes', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Lista de oferentes habilitados para participar en la subasta', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Listado de números radicados anulados', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Listado maestro de documentos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Listados de Asistencia', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Mantenimiento Red Vial Urbana', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Mantenimiento Vías Terciarias', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Manual de Funciones', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Manual de procesos y procedimientos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Matriz de Ruta Integral de atención', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Memoria justificativa', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Memorias de ayudas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Memorias de Calculo', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Minuta contractual', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Minuta de contrato o convenio', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Modificaciones', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Nómina', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Notas internas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Novedades', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Obligaciones', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Obras de Mitigación del Riesgo de Desastres', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Observaciones al proyecto pliego de condiciones', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Observaciones de los oferentes sobre las calificaciones', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Oficios remisiorios', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Orden de compra', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Orden de pago', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Pago Impuesto', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Pagos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Participacion en eventos empresariales', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Pasado Judicial - Certificado de Antecedentes Penales', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Pavimentación y Construcción de Vías', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Peritaje técnico', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Permiso tala de Arboles', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Permisos de Tránsito vehícullos de más de 2 ejes', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Permisos Laborales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'N', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Petición', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 0  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de capacitación', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan Agropecuario Municipal', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan anual de incentivos institucional', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de acción', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de Asistencia Técnica', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de atención de emergencias ambientales', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de Bienestar Social y Estimulo Laboral', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de contigencia', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de Desarrollo de Ecoturismo', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de manejo ambiental', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de Manejo de Tráfico', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de trabajo anual del Sistema De Seguridad y Salud en el Trabajo', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de Turismo Municipal', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de Vacaciones', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan de Vivienda de Interés Social', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan indicativo', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan Institucional de Archivos - PINAR', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => '"Plan Institucional de Gestión Ambiental ""PIGA"""', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan Local de Salud', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan Municipal de Juventud', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan operativo anual de inversión', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan Operativo Anual de Salud Pública', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plan Salud Pública de Intervenciones Colectivas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Planes Anuales de Adquisiciones', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Planillas de control de comunicaciones oficiales', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plano topografico', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Planos arquitectonicos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Planos de evacuación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Planos estructurales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Planos hidraulicos sanitarios y electricos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Planos hidraulicos sanitarios y electricos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Pliego de condiciones', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Plusvalia', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Poder autenticado (apoderado)', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Póliza', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Práctica de pruebas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Presentación del proyecto a la autoridad ambiental', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Prestamo maquinaria y equipo agropecuario', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Presupuesto Municipal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Proceso de Exclusión', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Procesos civiles en contra de la entidad', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Procesos civiles iniciados por la entidad', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Procesos contencioso administrativo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Procesos Laborales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Procesos Ordinarios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Procesos Penales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa anual de auditoria', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa Anual Mensualizado de Caja – PAC', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa de capacitación agropecuaria', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa de Gestión del Riesgo de Desastres', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa de Gobierno', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa de Infraestructura Gas natural', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa de Infraestructura Red Vial', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa de primera Infancia', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa de Salud Ocupacional', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa Mantenimiento Edificios Públicos Municipales', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa Mejoramiento Habitat', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programa Sostenibilidad Ambiental -GIRS', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programas Anuales Mensualizados de Caja PAC', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programas de gestión documental', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programas de Infraestructura Agua Potable y Saneamiento basico', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programas de infraestructura Redes Eléctricas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Programas de infraestructura Telefonía y Datos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Propuestas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Propuestas no seleccionadas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Proyecto', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Proyecto Parcelas Demostrativas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Proyectos de Mantenimiento de Bienes Muebles', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Pruebas', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Publicacion en pagina web', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Queja', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Radicado de Solicitud', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Ratificación y ampliación de queja Pruebas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Recibo a satisfacción', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Recibo de pago de impuesto', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Recibos Universales', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'reclamo', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Recurso de Consideración', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro de acuerdos comerciales', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro de asistencia', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro de Clasificación económica de los gastos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro de Modificaciones del PAC', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro de novedades de nómina', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro de Pagos programados de deuda pública', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro de Proyección de Planta de personal del año próximo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro de publicación en el SECOP', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro de publicación en página web', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro publicación en el SECOP', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro Único Tributario', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registro y Control del PAC', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Registros de Cálculo de los ingresos corrientes por producto', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Relación de bienes a dar baja', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Relación de descuentos de salud pensión parafiscales y cesantías', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Remisión de informe a la entidad correspondiente', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Reporte de comparendos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Reporte de incidentes', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Reporte SIIF', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Requerimiento Especial', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Requerimiento ordinario', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Resolución de apertura licitación o concurso', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Resolución de justificación de la contratación directa', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Resolución Declaratoria desierta', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Resolución para dar de baja los bienes', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Resoluciones', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Resoluciones definitivas de medidas de protección', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Respuesta', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Respuesta a observaciones al pliego de condiciones', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Respuesta Derecho de Petición', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Saneamiento y Manejo de Vertimientos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Seguimiento', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Seguimiento y Evaluación del POT vigente', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Serivicio de consulta asistencia', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Servicio de consulta agricola', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Servicio de consulta veterinaria', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud Interna', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'N', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud al Consultorio Jurídico de un defensor de oficio', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud al ordenador del gasto sobre adjudicación del proceso', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de adición o prórroga', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de adición o prórroga del convenio', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de bienes y servicios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de certificado de disponibilidad presupuestal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de contratación con lista de chequeo', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de disponibilidad presupuestal', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'N', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de fotocopias del expediente', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de información', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de ingreso de los bienes a almacén', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de la Proyección de Ingresos y/o Marco Fiscal Actualizado', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de permiso para tala de Arboles', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de personal', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de Presentación de Proyectos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de reposición y/o apelación', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de suministros', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud del PAC', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud elaboración de contrato', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud Salidas Turisticas', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solución a agua potable y alcantarillado', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solución a residuos liquidos', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Soportes contables', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Soportes de pago', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Soportes de remates', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Soportes documentales de estudios', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Sugerencias', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Suspendidos', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Tabla de control de acceso', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Tablas de retención documental', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Tablas de valoración documental', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Tarjeta de Propiedad', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Tutelas', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Verificaciones', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Felicitaciones', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'OTRO', 'used_entrance' => 'N', 'used_output' => 'N', 'used_pqrsd' => 'N', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'respuesta', 'used_entrance' => 'N', 'used_output' => 'Y', 'used_pqrsd' => 'N', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Traslado por competencia', 'used_entrance' => 'Y', 'used_output' => 'Y', 'used_pqrsd' => 'Y', 'status_id' => 1  ]);
        DB::table('documents_type')->insert(['name_' => 'Solicitud de permiso ambiental', 'used_entrance' => 'Y', 'used_output' => 'N', 'used_pqrsd' => 'N', 'status_id' => 1  ]);
    }
}
